functionsDirectory = "T:\\Desktop\\Privat\\CLUEF\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "T:\\Desktop\\Privat\\CLUEF"
publishOrigin = "default"
functions = "T:\\Desktop\\Privat\\CLUEF\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]